export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as FeaturedTemplates } from './FeaturedTemplates'
export { default as Pricing } from './Pricing'
export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as CustomizationForm } from './CustomizationForm'
export { Vortex } from './Vortex'
